fix(AbstractMapper): Cleanup mapper classes
Kitware/vtk-js pull request #2186
Opened 2021-12-02 21:58 UTC by DrewLazzeriKitware

These changes fix problems with Mapper classes found during https://github.com/Kitware/vtk-js/pull/2113.
Specifically:

- The class hierarchy for AbstractMapper was missing
- VolumeMapper was calling `macro.obj` and `macro.algo` (once through parent)
- AbstractMapper.removeClippingPlane was using indexes instead of instances
- AbstractMapper.removeClippingPlane was checking classes too specifically
- AbstractMapper methods were not calling modified.

BREAKING CHANGE:
Changed removeClippingPlane to use instance instead of index.

2021-12-02 22:02 UTC, DrewLazzeriKitware commented
@finetjul I've split the AbstractMapper improvements from the MPR https://github.com/Kitware/vtk-js/pull/2113 so they can be merged more easily. 

Please review.

2021-12-02 22:05 UTC, jourdain commented
LGTM

FYI @floryst @agirault @ebrahimebrahim

2021-12-03 15:37 UTC, daker requested changes

2021-12-03 15:54 UTC, DrewLazzeriKitware commented on Sources/Rendering/Core/AbstractMapper/index.d.ts
>  	 * @param {Number} i
Thanks good catch. Fixed.

2021-12-03 21:19 UTC, floryst commented
@DrewLazzeriKitware your AbstractMapper changes should be the desired one in resolving the conflict.

2021-12-04 00:46 UTC, DrewLazzeriKitware commented
@floryst The merge conflict is resolved

2021-12-05 16:36 UTC, finetjul commented
LGTM

2021-12-07 18:58 UTC, daker approved these changes
The typescript part is good for me.

2021-12-07 19:45 UTC, jourdain commented
@floryst since it is a BREAKING_CHANGE, I let you merge it when you see fit.

2022-01-10 21:24 UTC, merged