fix(AnnotatedCubeActor): add missing type annotations
Kitware/vtk-js pull request #2233
Opened 2022-01-18 18:33 UTC by yasushi-saito

### PR and Code Checklist

- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Context

`IO/Core/ImageStream/example` doesn't compile with typescript without this change.
This PR only changes the typescript definitions, not the actual js code.

### Changes

- [x] Documentation and TypeScript definitions were updated to match those changes

### Results

### Testing

- [ ] This change adds or fixes unit tests
- [ ] All tests complete without errors on the following environment:
  - **vtk.js**: 
  - **OS**: 
  - **Browser**: 

_This contribution is funded by [Example](https://example.com)._

2022-01-18 19:52 UTC, daker requested changes

2022-01-18 19:52 UTC, daker commented on Sources/Rendering/Core/AnnotatedCubeActor/index.d.ts
> +	resolution: number;
can you make it optional with `?`

2022-01-18 20:09 UTC, yasushi-saito commented on Sources/Rendering/Core/AnnotatedCubeActor/index.d.ts
> +	resolution: number;
done.

2022-01-18 20:15 UTC, daker approved these changes
LGTM

2022-01-19 09:12 UTC, finetjul commented
Please make it a "doc" type of commit instead of "fix".

2022-01-20 01:07 UTC, yasushi-saito commented
ok, done.

2022-01-20 06:14 UTC, merged

2022-01-20 06:14 UTC, finetjul commented
Thanks for your contribution !