fix(types): imageData optional arguments
Kitware/vtk-js pull request #2301
Opened 2022-03-04 01:13 UTC by sedghi

I'm not sure how `.d.ts` types are generated in `vtk.js`, probably manually?
I found two wrong type definitions and this PR fixes them.

Affected files:
- `Sources/Common/Core/MatrixBuilder` 
- `Sources/Common/DataModel/ImageData`

2022-03-04 14:22 UTC, jourdain commented
LGTM

2022-03-04 14:37 UTC, daker requested changes

2022-03-04 14:37 UTC, daker commented on Sources/Common/Core/MatrixBuilder/index.d.ts
>  	 * @param {Number} axis
if you can also fix the type here

2022-03-04 14:37 UTC, daker commented on Sources/Common/Core/MatrixBuilder/index.d.ts
> +	rotate(angle: number, axis: number[]): Transform
you can use the types from https://github.com/Kitware/vtk-js/blob/master/Sources/types.d.ts#L20-L22

2022-03-04 14:47 UTC, daker commented
@sedghi thanks for the fixes, yes .d.ts files are made manually, you need to change the commit scope to docs(ts): [...]

2022-03-04 17:43 UTC, sedghi commented
@daker Thank you, I applied your comments

2022-03-04 18:45 UTC, daker commented
@sedghi change the PR title to be the same as the commit message

2022-03-04 18:46 UTC, daker requested changes

2022-03-04 21:01 UTC, sedghi commented on Sources/Common/Core/MatrixBuilder/index.d.ts
> +	 * @param {Number[]} axis
Done, thanks

2022-03-04 21:04 UTC, daker commented
LGTM +1

2022-03-04 21:05 UTC, daker approved these changes

2022-03-08 14:29 UTC, floryst commented
LGTM

2022-03-08 15:50 UTC, merged