feat: add vtkSpherWidget
Kitware/vtk-js pull request #2323
Opened 2022-03-21 17:13 UTC by yasushi-saito

Add a widget for specifying a sphere.  It has two control handles, the center
and a border.  A border is an arbitrary point on the sphere border. It is used
to set the radius.

2022-03-21 23:17 UTC, daker requested changes

2022-03-22 14:58 UTC, yasushi-saito commented on Sources/Widgets/Widgets3D/SphereWidget/index.d.ts
> +  setCenterAndRadius(center: [number, number, number], radius: number): void;
OK, fixed.

2022-03-22 18:41 UTC, floryst approved these changes
LGTM!

2022-03-22 19:07 UTC, jourdain commented
@floryst I let you merge it in case you want to sync it with any other PR.

2022-03-25 16:29 UTC, merged