chore(vtkFieldData): update types
Kitware/vtk-js pull request #2568
Opened 2022-09-07 13:25 UTC by WesleyTheGeolien

### Context
updated types for vtkFielddata see #2567 

### Results
- typescript for field data is more expressive

### Changes
 updated `vtkFieldData.arrays` to be of type `vtkDataArray` instead of `any` I believe this is the only type the arrays should be

### PR and Code Checklist
- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [ ] Run `npm run reformat` to have correctly formatted code

### Testing
- [ ] This change adds or fixes unit tests 
- [ ] Tested environment:
  - **vtk.js**: latest master
  - **OS**: Mac OSX 12.5

2022-09-07 13:36 UTC, daker requested changes

2022-09-07 13:36 UTC, daker commented on Sources/Common/DataModel/DataSetAttributes/FieldData.d.ts
> +	arrays?: Array<vtkDataArray> | vtkDataArray[];
`vtkDataArray[]` is the short form of `Array<vtkDataArray>` , so you can just use `vtkDataArray[]`

2022-09-07 13:36 UTC, daker commented on Sources/Common/DataModel/DataSetAttributes/FieldData.d.ts
> +	getArrays(): Array<vtkDataArray> | vtkDataArray[];
same here

2022-09-07 13:40 UTC, daker commented
@WesleyTheGeolien also the commit message needs have a scope of docs(xxx) to prevent generating a new release

2022-09-08 08:07 UTC, WesleyTheGeolien commented
> @WesleyTheGeolien also the commit message needs have a scope of docs(xxx) to prevent generating a new release

sure @daker was not sure which category it all fell under! I guess the next release shouldn't be too far away and this will get into that anyway?

2022-09-08 13:27 UTC, merged