fix: adds more missing types
Kitware/vtk-js pull request #2756
Opened 2023-03-15 16:08 UTC by floryst

### Context

This PR adds more missing types to vtk.js

### Results

Better type coverage

### Changes

- [ ] Documentation and TypeScript definitions were updated to match those changes

### PR and Code Checklist

- [ ] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [ ] Run `npm run reformat` to have correctly formatted code

2023-03-15 17:59 UTC, daker requested changes

2023-03-15 17:59 UTC, daker commented on Sources/Rendering/OpenGL/HardwareSelector/index.d.ts
> +  ): PixelInformation | null;
`Nullable<PixelInformation>`

2023-03-20 20:01 UTC, floryst commented
Updated to use `Nullable`.

2023-03-20 20:10 UTC, daker approved these changes
LGTM

2023-03-20 20:13 UTC, daker requested changes

2023-03-20 20:13 UTC, daker commented on Sources/Rendering/Core/HardwareSelector/index.d.ts
> +   * @param {number} fy1 bottom right x coord
fx2 instead?

2023-03-20 20:13 UTC, daker commented on Sources/Rendering/Core/HardwareSelector/index.d.ts
> +   */
Same here

2023-03-20 20:21 UTC, floryst commented on Sources/Rendering/Core/HardwareSelector/index.d.ts
> +   * @param {number} fy1 bottom right x coord
I've fixed these comments.

2023-03-20 20:33 UTC, daker approved these changes
LGTM

2023-03-22 14:15 UTC, merged