fix(imagemapper): adding types for slicingMode and preferSizeOverAccu…
Kitware/vtk-js pull request #2916
Opened 2023-09-13 20:09 UTC by jmargeta

### Context
This adds extra typing for missing setters and getters for slicingMode and preferSizeOverAccuracy in ImageMapper. 

### Results and Changes
- added types for setSlicingMode(number), getPreferSizeOverAccuracy(bool), setPreferSizeOverAccuracy(bool)
- [x] Documentation and TypeScript definitions were updated to match those changes

### PR and Code Checklist
- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Testing
- [ ] This change adds or fixes unit tests
- [x] Tested environment:
  - **vtk.js**: 28.11.0
  - **OS**: Ubuntu 22.04 (WSL)
  - **Browser**: Firefox 117.9.1

2023-09-14 08:15 UTC, daker requested changes
Left some comments

2023-09-14 08:15 UTC, daker commented on Sources/Rendering/Core/ImageMapper/index.d.ts
> +	getSlicingMode(): number;
Can you use the `SlicingMode` from `Constants.d.ts`? if you change also for the setter that would be good.

2023-09-14 10:48 UTC, jmargeta commented
Thanks for the review @daker, I applied and pushed your suggestions.

2023-09-14 11:25 UTC, daker approved these changes
LGTM

2023-09-18 17:59 UTC, floryst commented
LGTM! Thanks!

2023-09-20 14:58 UTC, merged