fix(type): fix type returned when inserting a point
Kitware/vtk-js pull request #3049
Opened 2024-03-27 20:43 UTC by ramonemiliani93

Fix #3048

### Context
Fixes the interface of the `insertNextPoint` method on the  `vtkPoints` class.

### Results
Updates the interface on the `Points.d.ts` file.

### Changes
- [X] Documentation and TypeScript definitions were updated to match those changes

### PR and Code Checklist

- [X] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [X] Run `npm run reformat` to have correctly formatted code

### Testing

- [ ] This change adds or fixes unit tests 
- [ ] Tested environment:
  - **vtk.js**: 
  - **OS**: 
  - **Browser**:

2024-03-27 21:09 UTC, finetjul requested changes

2024-03-27 21:09 UTC, finetjul commented on Sources/Common/Core/Points/index.d.ts
> +   * @returns {Number} Index of the inserted point.
please fix the indent

2024-03-27 21:25 UTC, finetjul approved these changes
LGTM. Thanks !

2024-03-30 01:27 UTC, daker approved these changes
LGTM

2024-05-30 17:19 UTC, merged