fix(ImageResliceMapper): Axis orthogonality cannot be correctly identified when using slicePlane
Kitware/vtk-js pull request #3064
Opened 2024-04-28 17:40 UTC by yarous224

`const w2io = mat3.fromValues(image?.getDirection());` 

`mat3.fromValues`needs expanded array, the old version would output a matrix full of NaN here.

### Context

### Results

### Changes

- [ ] Documentation and TypeScript definitions were updated to match those changes

### PR and Code Checklist

- [ ] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [ ] Run `npm run reformat` to have correctly formatted code

### Testing

- [ ] This change adds or fixes unit tests 
- [ ] Tested environment:
  - **vtk.js**: 
  - **OS**: 
  - **Browser**:

2024-05-28 02:51 UTC, yarous224 commented
### Image Size
The polygons generated by ImageResliceMapper do not take into account the size of the pixels themselves.

This is a 512*512 spacing 0.782 image. It length is 400.384mm.
#### Before Change:
<img width="431" alt="bb54c760cd380cfb238e11fbe86a197" src="https://github.com/Kitware/vtk-js/assets/18617494/cb72846e-a401-4eee-af62-817d097a4333">

#### After Change:
<img width="387" alt="55aae1f4723109b03716f057b2a90da" src="https://github.com/Kitware/vtk-js/assets/18617494/8c790391-364d-4c7a-9194-5436b331af5c">

2024-05-28 03:19 UTC, yarous224 commented
### Texture coordinates
ImageResliceMapper does not account for the 0.5 offset of the texture matrix when calculating the matrix from world coordinates to texture coordinates, resulting in behavior that is inconsistent with other software (e.g., Radiant).

Before Change
![image](https://github.com/Kitware/vtk-js/assets/18617494/d57ebf4c-d2ad-47bf-acff-464fca8dbbe9)
After Change
![image](https://github.com/Kitware/vtk-js/assets/18617494/61df8542-5d6c-4f89-af5c-6fadcf187e5c)
Radiant
![image](https://github.com/Kitware/vtk-js/assets/18617494/88d5b21b-2d3c-4e63-aebc-f967fc8c1284)

2024-05-30 17:15 UTC, floryst commented
@sankhesh can you take a look?

2024-05-30 19:38 UTC, sankhesh requested changes

2024-05-30 19:38 UTC, sankhesh commented on Sources/Rendering/OpenGL/ImageResliceMapper/index.js
> +          const ext = [
Please use `image.getSpatialExtent` here.

2024-05-30 19:38 UTC, sankhesh commented on Sources/Rendering/OpenGL/ImageResliceMapper/index.js
> +        // Check to see if we can bypass oblique slicing related bounds computation
I'm not sure I follow the reason for this change. Firstly, this function will not be called unless there is an input(https://github.com/Kitware/vtk-js/blob/a8b7a5cf99c546f28d92bad21ac71a3404c1bff8/Sources/Rendering/OpenGL/ImageResliceMapper/index.js#L121-L126). Secondly, even if execution gets here without an input, an xy plane should still be detected as orthonormal.

2024-12-19 22:29 UTC, daker commented
@yarous224 i believe your commits have been merged in the other PR, can you close this one ?

2024-12-26 16:10 UTC, floryst commented
Based on the conversations, it appears that this PR has been superseded in #3093. Please re-open with a comment if this is not the case.

2024-12-26 16:10 UTC, closed without merging