feat(HDRReader): add vtkHDRReader
Kitware/vtk-js pull request #3146
Opened 2024-10-14 14:08 UTC by daker

### Context
This PR adds support for loading HDR images

Fixes #3145

### Results
![image](https://github.com/user-attachments/assets/fd20d8cf-fcae-412e-9f51-91106f80ac6f)

### Changes
- [x] Documentation and TypeScript definitions were updated to match those changes

### PR and Code Checklist
- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Testing
- [ ] This change adds or fixes unit tests 
- [ ] Tested environment:
  - **vtk.js**: 
  - **OS**: 
  - **Browser**:

2024-10-14 16:13 UTC, finetjul commented on Sources/IO/Image/HDRReader/index.js
> +  publicAPI.getHeight = () => model.dataExtent[3] - model.dataExtent[2] + 1;
maybe `return model.output[0].getDimensions()[0]` (with some failsafe ?)

2024-10-14 16:13 UTC, finetjul commented on Sources/IO/Image/HDRReader/index.js
> +    model.dataSpacing[2] = 1;
do not store in reader, all the information should be in the image data

2024-10-14 16:13 UTC, finetjul commented on Sources/IO/Image/HDRReader/index.js
> +    imageData.setOrigin(0, 0, 0);
isn't origin already at 0,0,0 ?

2024-10-14 16:13 UTC, finetjul commented on Sources/IO/Image/HDRReader/index.js
> +  pixelAspect: 1.0,
does not seem to be used

2024-10-14 20:10 UTC, daker commented on Sources/IO/Image/HDRReader/example/index.js
> +import '@kitware/vtk.js/favicon';
Can you share the image template with the icon ?

2024-10-15 06:24 UTC, finetjul commented on Sources/IO/Image/HDRReader/example/index.js
> +import '@kitware/vtk.js/favicon';
[File VTK.js icons.pptx](https://github.com/user-attachments/files/17373563/File.VTK.js.icons.pptx)
Here you go

2024-10-15 09:47 UTC, finetjul requested changes

2024-10-15 09:47 UTC, finetjul commented on Sources/IO/Image/HDRReader/Utils.js
> +import * as vtkMath from '@kitware/vtk.js/Common/Core/Math';
`import * as vtkMath from 'vtk.js/Sources/Common/Core/Math';`

2024-10-15 09:47 UTC, finetjul commented on Sources/IO/Image/HDRReader/index.js
> +import * as vtkMath from '@kitware/vtk.js/Common/Core/Math';
import * as vtkMath from 'vtk.js/Sources/Common/Core/Math';

2024-10-15 16:06 UTC, finetjul approved these changes
LGTM

2024-10-21 20:00 UTC, daker commented
@floryst i rebased the branch

2024-10-21 20:47 UTC, floryst commented
Thanks!

2024-10-21 20:54 UTC, merged