feat(IFCImporter): add vtkIFCImporter
Kitware/vtk-js pull request #3168
Opened 2024-11-05 16:20 UTC by daker

This PR adds support for IFC format, the importer allows to merge geometries to reduce the number of actors in the scene.

### Context
fixes #3156

### Results

### Changes
- [x] Documentation and TypeScript definitions were updated to match those changes

### PR and Code Checklist
- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Testing
- [x] This change adds or fixes unit tests 
- [x] Tested environment:
  - **vtk.js**: 
  - **OS**: 
  - **Browser**:

2024-11-05 17:03 UTC, finetjul commented on Sources/IO/Geometry/IFCImporter/index.js
> +function setIFCAPI(api) {
Should be documented, it's not clear what this is for

2024-11-05 17:03 UTC, finetjul commented
> @finetjul i still need to fix the normals transformation when the geometries are merged, if you have any hints.

I think Matrix builder has a function to transform vectors(normals)

2024-11-06 00:16 UTC, daker commented on Sources/IO/Geometry/IFCImporter/example/index.js
> +  .loadScript('https://cdn.jsdelivr.net/npm/web-ifc@0.0.55/web-ifc-api-iife.js')
i don't have an account, can you upload that and share the link ?

2024-11-08 16:38 UTC, finetjul requested changes

2024-11-08 22:11 UTC, daker commented on Sources/IO/Geometry/IFCImporter/index.js
> + */
it's already there

https://github.com/Kitware/vtk-js/pull/3168/files#diff-12358842b72292fad557d196b017e2c81f49c03965de4099cf9ab7f409df9a4dR104

2024-11-08 23:08 UTC, daker commented on Data/ifc/house.ifc
I did a demo file from the Web IFC repo directly

2024-11-08 23:14 UTC, daker commented on Sources/IO/Geometry/IFCImporter/index.js
> +        actor.setUserMatrix(mesh.userMatrix);
i did apply the matrix in `createColoredPolyDataFromIFCMesh`

2024-11-14 07:39 UTC, finetjul requested changes
Can you please add a screenshot in the example gallery.

2024-11-17 17:48 UTC, daker commented
@finetjul it's ready

2024-11-18 08:02 UTC, finetjul approved these changes
LGTM

2024-12-03 00:28 UTC, daker commented
@floryst this is ready too :) i have another PR waiting for your review #3170

2024-12-04 20:12 UTC, floryst approved these changes

2024-12-05 16:17 UTC, merged